// StandardMenuDefinitions.h

/*
 * This header contains the private definitions used internally by Maze.
 */


#ifndef STANDARD_MENU_DEFINITIONS_H
#define STANDARD_MENU_DEFINITIONS_H

#include "Maze.h"


//TODO: consider: is de extra stap in insert/delete/change nodig (in Maze) WAT doet die?
static const MZ_menuActionT menuActions[MZ_STATE_COUNT][MZ_NAV_COUNT] = {
    [MZ_STATE_SCROLLING] = {
        [MZ_NAV_ENTER]          = MZ_ACTION_SELECT_MENU_ITEM,
        [MZ_NAV_UP]             = MZ_ACTION_SCROLL_1_MENU_ITEM_BACK_OR_GO_TO_HEADER,
        [MZ_NAV_UP10]           = MZ_ACTION_SCROLL_10_MENU_ITEMS_BACK,
        [MZ_NAV_DOWN]           = MZ_ACTION_SCROLL_1_MENU_ITEM_FORWARD,
        [MZ_NAV_DOWN10]         = MZ_ACTION_SCROLL_10_MENU_ITEMS_FORWARD,
        [MZ_NAV_LEFT]           = MZ_ACTION_GO_TO_MANAGE_RECORDS,
        [MZ_NAV_RIGHT]          = MZ_ACTION_GO_TO_EDIT_RECORD,
        [MZ_NAV_GO_TO_HIDDEN]   = MZ_ACTION_GO_TO_HIDDEN_MENU,
    },
    [MZ_STATE_IN_HEADER] = {
        [MZ_NAV_ENTER]      = MZ_ACTION_GO_TO_PARENT_OR_RETURN_HEADER_ACTION,
        [MZ_NAV_LEFT]       = MZ_ACTION_GO_TO_PREVIOUS_HEADER_POSITION,
        [MZ_NAV_RIGHT]      = MZ_ACTION_GO_TO_NEXT_HEADER_POSITION,
        [MZ_NAV_DOWN]       = MZ_ACTION_LEAVE_HEADER,
    },
    [MZ_STATE_DBASE_EDITING] = {
        [MZ_NAV_RIGHT]      = MZ_ACTION_GO_1_COLUMN_FORWARD,
        [MZ_NAV_LEFT]       = MZ_ACTION_GO_1_COLUMN_BACK,
        [MZ_NAV_END]        = MZ_ACTION_GO_10_COLUMNS_FORWARD,
        [MZ_NAV_HOME]       = MZ_ACTION_GO_10_COLUMNS_BACK,
        [MZ_NAV_UP]         = MZ_ACTION_INCREASE_VALUE_BY_1,
        [MZ_NAV_DOWN]       = MZ_ACTION_DECREASE_VALUE_BY_1,
        [MZ_NAV_UP10]       = MZ_ACTION_INCREASE_VALUE_BY_10,
        [MZ_NAV_DOWN10]     = MZ_ACTION_DECREASE_VALUE_BY_10,
    },
    [MZ_STATE_DBASE_GOTO_CHANGE_RECORD_TYPE] = {
        [MZ_NAV_ENTER]      = MZ_ACTION_GOTO_CHANGE_RECORD_TYPE,
        [MZ_NAV_LEFT]       = MZ_ACTION_GOTO_INSERT_RECORD,
        [MZ_NAV_RIGHT]      = MZ_ACTION_LEAVE_MANAGE_RECORDS,
        [MZ_NAV_UP]         = MZ_ACTION_LEAVE_MANAGE_RECORDS,
        [MZ_NAV_DOWN]       = MZ_ACTION_LEAVE_MANAGE_RECORDS,
    },
    [MZ_STATE_DBASE_CHANGE_RECORD_TYPE] = {
        [MZ_NAV_LEFT]       = MZ_ACTION_GOTO_INSERT_RECORD,
        [MZ_NAV_RIGHT]      = MZ_ACTION_LEAVE_MANAGE_RECORDS,
        [MZ_NAV_UP]         = MZ_ACTION_INCREASE_VALUE_BY_1,
        [MZ_NAV_DOWN]       = MZ_ACTION_DECREASE_VALUE_BY_1,
        [MZ_NAV_UP10]       = MZ_ACTION_INCREASE_VALUE_BY_10,
        [MZ_NAV_DOWN10]     = MZ_ACTION_DECREASE_VALUE_BY_10,
    },
    [MZ_STATE_DBASE_INSERT_RECORD] = {
        [MZ_NAV_ENTER]      = MZ_ACTION_INSERT_RECORD,
        [MZ_NAV_LEFT]       = MZ_ACTION_GOTO_DELETE_RECORD,
        [MZ_NAV_RIGHT]      = MZ_ACTION_LEAVE_INSERT_RECORD,
        [MZ_NAV_UP]         = MZ_ACTION_LEAVE_MANAGE_RECORDS,
        [MZ_NAV_DOWN]       = MZ_ACTION_LEAVE_MANAGE_RECORDS,
    },
    [MZ_STATE_DBASE_CANNOT_INSERT_RECORD] = {
        [MZ_NAV_LEFT]       = MZ_ACTION_GOTO_DELETE_RECORD,
        [MZ_NAV_RIGHT]      = MZ_ACTION_LEAVE_INSERT_RECORD,
        [MZ_NAV_UP]         = MZ_ACTION_LEAVE_MANAGE_RECORDS,
        [MZ_NAV_DOWN]       = MZ_ACTION_LEAVE_MANAGE_RECORDS,
    },
    [MZ_STATE_DBASE_DELETE_RECORD] = {
        [MZ_NAV_ENTER]      = MZ_ACTION_DELETE_RECORD,
        [MZ_NAV_RIGHT]      = MZ_ACTION_GOTO_INSERT_RECORD,
        [MZ_NAV_UP]         = MZ_ACTION_LEAVE_MANAGE_RECORDS,
        [MZ_NAV_DOWN]       = MZ_ACTION_LEAVE_MANAGE_RECORDS,
    },
    [MZ_STATE_DBASE_CANNOT_DELETE_RECORD] = {
        [MZ_NAV_UP]         = MZ_ACTION_LEAVE_MANAGE_RECORDS,
        [MZ_NAV_DOWN]       = MZ_ACTION_LEAVE_MANAGE_RECORDS,
        [MZ_NAV_RIGHT]      = MZ_ACTION_GOTO_INSERT_RECORD,
    },
};


#endif
