// StandardMenuDefinitions.h

/*
 * Standard definitions used internally by Maze.
 * User-defined menu types/states/actions may be added independently
 * without modifying this file.
 */


#ifndef STANDARD_MENU_DEFINITIONS_H
#define STANDARD_MENU_DEFINITIONS_H

#include "Maze.h"


static const MZ_menuTypeDefT MenuTypeDefs[MZ_MENU_TYPE_COUNT] = {
    [MZ_MENU_TYPE_TEXT] = {
        .defaultState = MZ_STATE_STD_SCROLLING,
    },
    [MZ_MENU_TYPE_DBASE] = {
        .defaultState = MZ_STATE_DBASE_SCROLLING,
    },
};


//1x intern (prive) en 1x extern
static const MZ_menuActionT menuActions[MZ_STATE_COUNT][MZ_NAV_COUNT] = {
    [MZ_STATE_STD_SCROLLING] = {
        [MZ_NAV_ENTER]      = MZ_ACTION_GO_TO_MENU,
        [MZ_NAV_UP]         = MZ_ACTION_SCROLL_1_MENU_ITEM_BACK,
        [MZ_NAV_UP10]       = MZ_ACTION_SCROLL_10_MENU_ITEMS_BACK,
        [MZ_NAV_DOWN]       = MZ_ACTION_SCROLL_1_MENU_ITEM_FORWARD,
        [MZ_NAV_DOWN10]     = MZ_ACTION_SCROLL_10_MENU_ITEMS_FORWARD,
    },
    [MZ_STATE_DBASE_SCROLLING] = {
        [MZ_NAV_ENTER]      = MZ_ACTION_GO_TO_MENU_FROM_DB,
        [MZ_NAV_UP]         = MZ_ACTION_SCROLL_1_MENU_ITEM_BACK,
        [MZ_NAV_UP10]       = MZ_ACTION_SCROLL_10_MENU_ITEMS_BACK,
        [MZ_NAV_DOWN]       = MZ_ACTION_SCROLL_1_MENU_ITEM_FORWARD,
        [MZ_NAV_DOWN10]     = MZ_ACTION_SCROLL_10_MENU_ITEMS_FORWARD,
        [MZ_NAV_RIGHT]      = MZ_ACTION_ENTER_EDIT_RECORD,
        [MZ_NAV_LEFT]       = MZ_ACTION_MANAGE_RECORDS,
    },
    [MZ_STATE_DBASE_EDITING] = {
        [MZ_NAV_RIGHT]      = MZ_ACTION_GO_1_COLUMN_FORWARD,
        [MZ_NAV_LEFT]       = MZ_ACTION_GO_1_COLUMN_BACK,
        [MZ_NAV_END]        = MZ_ACTION_GO_10_COLUMNS_FORWARD,
        [MZ_NAV_HOME]       = MZ_ACTION_GO_10_COLUMNS_BACK,
        [MZ_NAV_PLUS1]      = MZ_ACTION_INCREASE_VALUE_BY_1,
        [MZ_NAV_MINUS1]     = MZ_ACTION_DECREASE_VALUE_BY_1,
        [MZ_NAV_PLUS10]     = MZ_ACTION_INCREASE_VALUE_BY_10,
        [MZ_NAV_MINUS10]    = MZ_ACTION_DECREASE_VALUE_BY_10,
    },
    [MZ_STATE_DBASE_GOTO_CHANGE_RECORD_TYPE] = {
        [MZ_NAV_ENTER]      = MZ_ACTION_GOTO_CHANGE_RECORD_TYPE,
        [MZ_NAV_LEFT]       = MZ_ACTION_GOTO_INSERT_RECORD,
        [MZ_NAV_RIGHT]      = MZ_ACTION_LEAVE_MANAGE_RECORDS,
    },
    [MZ_STATE_DBASE_CHANGE_RECORD_TYPE] = {
        [MZ_NAV_LEFT]       = MZ_ACTION_GOTO_INSERT_RECORD,
        [MZ_NAV_RIGHT]      = MZ_ACTION_LEAVE_MANAGE_RECORDS,
        [MZ_NAV_PLUS1]      = MZ_ACTION_INCREASE_VALUE_BY_1,
        [MZ_NAV_MINUS1]     = MZ_ACTION_DECREASE_VALUE_BY_1,
        [MZ_NAV_PLUS10]     = MZ_ACTION_INCREASE_VALUE_BY_10,
        [MZ_NAV_MINUS10]    = MZ_ACTION_DECREASE_VALUE_BY_10,
    },
    [MZ_STATE_DBASE_INSERT_RECORD] = {
        [MZ_NAV_ENTER]      = MZ_ACTION_INSERT_RECORD,
        [MZ_NAV_LEFT]       = MZ_ACTION_GOTO_DELETE_RECORD,
        [MZ_NAV_RIGHT]      = MZ_ACTION_LEAVE_INSERT_RECORD,
        [MZ_NAV_UP]         = MZ_ACTION_LEAVE_MANAGE_RECORDS,
        [MZ_NAV_DOWN]       = MZ_ACTION_LEAVE_MANAGE_RECORDS,
    },
    [MZ_STATE_DBASE_CANNOT_INSERT_RECORD] = {
        [MZ_NAV_LEFT]       = MZ_ACTION_GOTO_DELETE_RECORD,
        [MZ_NAV_RIGHT]      = MZ_ACTION_LEAVE_INSERT_RECORD,
        [MZ_NAV_UP]         = MZ_ACTION_LEAVE_MANAGE_RECORDS,
        [MZ_NAV_DOWN]       = MZ_ACTION_LEAVE_MANAGE_RECORDS,
    },
    [MZ_STATE_DBASE_DELETE_RECORD] = {
        [MZ_NAV_ENTER]      = MZ_ACTION_DELETE_RECORD,
        [MZ_NAV_RIGHT]      = MZ_ACTION_GOTO_INSERT_RECORD,
        [MZ_NAV_UP]         = MZ_ACTION_LEAVE_MANAGE_RECORDS,
        [MZ_NAV_DOWN]       = MZ_ACTION_LEAVE_MANAGE_RECORDS,
    },
    [MZ_STATE_DBASE_CANNOT_DELETE_RECORD] = {
        [MZ_NAV_UP]         = MZ_ACTION_LEAVE_MANAGE_RECORDS,
        [MZ_NAV_DOWN]       = MZ_ACTION_LEAVE_MANAGE_RECORDS,
        [MZ_NAV_RIGHT]      = MZ_ACTION_GOTO_INSERT_RECORD,
    },
};


#endif
